### ISSUE TITLE
Simulated Time

### ISSUE THREAD

**Issue by tomcodewizard** [ala1705/pk_models#11]
Should we try and be able to change the time that the model runs for? Could be an extra parameter in the model, perhaps with a preset value, e.g. run-time=1000

**Comment by tomcodewizard** [comment]
Implementation of it will be dependent on how we pass through our inputs

**Comment by tomcodewizard** [comment]
I have added a run_time and num_timesteps variable into the class configurations, so that the task should now be fulfilled.
It has had limited manual testing, so will require more.

**Comment by mghosh00** [comment]
This is all done!!
