### ISSUE TITLE
Plots

### ISSUE THREAD

**Issue by tomcodewizard** [ala1705/pk_models#3]
Currently code creates a single comparison plot. This needs testing.
Do we want to add option to save individual plots too?

**Comment by tomcodewizard** [comment]
plot.py currently creates a plot with all q-values against time for a single model

The requirements wish for a comparison plot to plot two models against each-other, i.e. the q-values of model 1 alongside the q-values of model 2, all against time.

The problem comes from saving the data after running model 1, so that model 2 can be run and both outputs be plotted alongside each-other.

We have discussed saving the data from model 1 to a file, so that a comparison plot can be made once model 2 is run.

Current Issues needed to be solved for this problem:

- How we save the data to a file, i.e. what is the structure, so that we know what is to be read
- Label each array of q-values by the model and by which compartment it represents
- Reading data from the file
- How does the user let us know if they want a comparison plot (Maybe they just want to run 1 model, or maybe compare 3 models...?)
- Do we allow the user to create individual plots of q-values of one compartment for a model? (and maybe one compartment for two models even?)
- Where do we save the plots? How are they named? How can we guarantee the directories exist and data is not accidentally overwritten?

As this problem is attempted, more issues will become apparent, but these are my initial thoughts

**Comment by mghosh00** [comment]
Would work on this if we had more time
