### ISSUE TITLE
Plot labelling

### ISSUE THREAD

**Issue by mghosh00** [ala1705/pk_models#4]
Can you label the plots more clearly with a title??

**Comment by tomcodewizard** [comment]
plot.py has been updated and pushed

**Comment by mghosh00** [comment]
You haven't fixed this!!! Change the titles please to include Intravenous or Subcutaneous in the title of the model

**Comment by tomcodewizard** [comment]
Titles have been changed with correct model name

Also, plots are given unique names and solved to a folder in directory

**Comment by mghosh00** [comment]
Nice job!!
