### ISSUE TITLE
Manual testing

### ISSUE THREAD

**Issue by mghosh00** [ala1705/pk_models#9]
It would be good to do some manual tests on the plots to make sure that the outputted results are what we expect

**Comment by tomcodewizard** [comment]
Seems to work fine for when there are no peripheries, as long as the array inputs are given as empty sets []

**Comment by tomcodewizard** [comment]
Code allows rates of 0 but only volumes > 0

**Comment by tomcodewizard** [comment]
number_peripheries not necessary as we input arrays. Could alternatively check to see if both list lengths are the same.
Not highest priority so just a suggestion

**Comment by mghosh00** [comment]
Manual testing complete
